# -*- coding: utf-8 -*-
"""AIESEC_IGTa_Proto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C8UaBkco6_ZfTJxGi9lJA2um-EGPYeVW
"""

import pandas as pd

# Path to your CSV (replace only if filename changes)
csv_path = "Internship Job Questionnaire (Responses) - Form Responses 1.csv"

# Load CSV
df = pd.read_csv(csv_path)

# Normalize column names once (safety)
df.columns = df.columns.str.strip().str.lower()

# Filter rows where Opportunity ID is missing
missing_rows = df[
    df["opportunity id"].isna() |
    (df["opportunity id"].astype(str).str.strip() == "")
]

# Convert DataFrame index → Google Sheet row numbers
row_numbers = missing_rows.index + 2

# Output
for r in row_numbers:
    print(r)

import pandas as pd

# -------- CONFIG --------
csv_path = "Internship Job Questionnaire (Responses) - Form Responses 1.csv"
SHEET_ROW_NUMBER = 3   # 👈🏽👈🏽👈🏽 change this
# ------------------------

# Load CSV
df = pd.read_csv(csv_path)

# Normalize column names
df.columns = df.columns.str.strip().str.lower()

# Convert sheet row → dataframe index
df_index = SHEET_ROW_NUMBER - 2

if df_index < 0 or df_index >= len(df):
    raise ValueError("Invalid sheet row number")

row = df.iloc[df_index]

print("\n----- OPPORTUNITY DETAILS -----\n")
for col in df.columns:
    print(f"{col.upper()}: {row[col]}")
print("\n--------------------------------\n")

import pandas as pd

# -------- CONFIG --------
expa_role = str(row.get("opportunity title", "")).strip()
print("Role Title:", expa_role)
# ------------------------

# Load CSV
df = pd.read_csv(csv_path)
df.columns = df.columns.str.strip().str.lower()

row = df.iloc[SHEET_ROW_NUMBER - 2]
title = row["opportunity title"].lower()

def classify_role(title):
    # ⬇️ PASTE INVALID CHECK HERE
    title = title.lower().strip()

    invalid_exact_titles = {...}

    if title in invalid_exact_titles:
        return "❌ INVALID TITLE (Needs Manual Fix)"


# PHARMACEUTICAL / CLINICAL / DRUG DOMAIN
    if any(k in title for k in [
        "pharma", "pharmacy", "drug", "clinical",
        "regulation", "regulatory", "cocrystal",
        "anticancer", "in vitro", "screening",
        "nash", "formulation"
    ]):
        return "Pharmaceutical Intern"

    # -------- BIOMEDICAL / BIO --------
    if any(k in title for k in [
        "biomedical", "biosensing", "respiratory", "artery",
        "stent", "patient", "clinical", "wound",
        "cardio", "health monitoring", "mr image", "zebrafish"
    ]):
        return "Biomedical Engineering Intern"

    # -------- BIO / LIFE SCIENCES --------
    if any(k in title for k in [
        "bioinformatics", "in vitro", "molecular",
        "medicinal plant", "secondary metabolite", "toxicity"
    ]):
        return "Biological Sciences Intern"

    # -------- MECHANICAL / CFD / FEA --------
    if any(k in title for k in [
        "cfd", "finite element", "fem", "fea",
        "aerodynamics", "thermal", "structures",
        "pneumatic", "sandwich structure"
    ]):
        return "Mechanical Engineering Intern"

    # -------- ELECTRICAL / ELECTRONICS --------
    if any(k in title for k in [
        "fpga", "microcontroller", "pwm", "motor",
        "smart grid", "control system", "embedded",
        "cyber security", "quantum computing"
    ]):
        return "Electrical & Electronics Engineering Intern"

    # -------- MATERIALS / CHEM / PHARMA --------
    if any(k in title for k in [
        "nanomaterial", "thin film", "coating",
        "catalyst", "co-crystal", "anticancer",
        "pharmaceutical", "drug", "screening"
    ]):
        return "Chemical / Materials Science Intern"

    # -------- ENERGY / EV / ENVIRONMENT --------
    if any(k in title for k in [
        "energy", "electric vehicle", "wind",
        "renewable", "storage", "e-mobility",
        "carbon dioxide", "emission", "green cover"
    ]):
        return "Energy / Environmental Engineering Intern"

    # -------- DATA / AI / COMPUTATION --------
    if any(k in title for k in [
        "computational", "deep learning", "machine learning",
        "optimization", "multi-agent", "tracking",
        "digital twin", "simulation", "model"
    ]):
        return "Data / AI Engineering Intern"

    # -------- ARCHITECTURE / DESIGN --------
    if any(k in title for k in [
        "architecture", "architectural", "design"
    ]):
        return "Architecture / Design Intern"

    # -------- SOCIAL SCIENCE / POLICY --------
    if any(k in title for k in [
        "education", "disabilities", "religion",
        "women", "pedestrian", "cities", "policy",
        "transcultural"
    ]):
        return "Social Sciences / Policy Intern"

    # -------- BUSINESS / FINANCE --------
    if any(k in title for k in [
        "banking", "finance", "consumer",
        "marketing", "management", "business"
    ]):
        return "Business / Finance Intern"

    # -------- FALLBACK --------
    return "General Engineering Intern"


final_title = classify_role(title)

print("ORIGINAL TITLE:")
print(row["opportunity title"])

print("\nEXPA ROLE TITLE:")
print(final_title)

import pandas as pd

# ---------- Load CSV ----------
df = pd.read_csv(MAIN_CSV)
df.columns = df.columns.str.strip().str.lower()

# Convert sheet row to dataframe index
df_index = SHEET_ROW_NUMBER - 2

if df_index < 0 or df_index >= len(df):
    raise ValueError("Invalid SHEET_ROW_NUMBER")

row = df.iloc[df_index]

# Extract role title dynamically
expa_role = str(row.get("opportunity title", "")).strip()


# ---------- EXPA DETAILS (Hardcoded Org Info) ----------
ORGANISATION_NAME = "M.A.H.E"

ORGANISATION_DESCRIPTION = (
    "M.A.H.E. is a premier research institute in various disciplines and has been "
    "awarded the 'Institute of Eminence' title. Founded in 1953, M.A.H.E. has "
    "pioneered education and has been the alma mater for many successful individuals."
)

LOCATION = "Manipal, Karnataka, India"


def map_sub_product(expa_role_title):

    role = expa_role_title.lower()

    if any(k in role for k in [
        "engineering", "pharmaceutical", "biomedical",
        "materials", "chemical", "energy",
        "mechanical", "electrical", "civil",
        "architecture"
    ]):
        return "Engineering"

    if any(k in role for k in [
        "data", "ai", "computer", "information technology",
        "cyber"
    ]):
        return "Information Technology"

    if "finance" in role:
        return "Finance"

    if "marketing" in role:
        return "Marketing"

    if any(k in role for k in [
        "business", "management", "operations"
    ]):
        return "Business Administration"

    return "Other"


# Get sub-product dynamically
sub_product = map_sub_product(expa_role)


# ---------- OUTPUT FOR EXPA ----------
print("\n========== EXPA DETAILS ==========\n")

print("Organisation Name:")
print(ORGANISATION_NAME)

print("\nOrganisation Description:")
print(ORGANISATION_DESCRIPTION)

print("\nLocation:")
print(LOCATION)

print("\nRole Title:")
print(expa_role)

print("\nSub-product:")
print(sub_product)

# ================= PROMPT TEMPLATES (PERSONALISED FOR AIESEC MAHE) =================

ROLE_DESCRIPTION_PROMPT = """
You are assisting AIESEC MAHE (Manipal Academy of Higher Education), India, in drafting a Role Description
for an internship opportunity to be posted on the AIESEC EXPA Global Talent platform.

Using ONLY the information provided below:
- Opportunity Title
- Existing Role Description (if any)
- Tasks the intern will be doing
- Preferred Academic Background (if mentioned)

Write a detailed yet professional Role Description of approximately 5–7 sentences.

Guidelines:
- Maintain an academic and research-oriented tone.
- Clearly describe the nature of the work, the technical or research context, and the type of activities involved.
- Explain what the intern will be exposed to or trained in, without overstating responsibility or impact.
- Avoid exaggeration, promotional language, or claims about outcomes.
- Do NOT use phrases such as “world-class”, “cutting-edge”, or “unique opportunity”.
- Write in third person and keep the description suitable for international students applying through AIESEC.
- The description should give a clear picture of what the intern will be doing on a day-to-day basis.

Information:
"""


TASKS_PROMPT = """
You are assisting AIESEC MAHE (Manipal Academy of Higher Education), India, in structuring
the “Tasks the Intern Will Be Doing” section for an internship opportunity to be posted
on the AIESEC EXPA Global Talent platform.

Using ONLY the information provided below, rewrite the tasks into exactly 5 detailed
and well-articulated bullet points.

Guidelines:
- Each bullet point must begin with a clear action verb (Assist, Conduct, Analyze, Design, Develop, Support, etc.).
- Each point should contain 1–2 full descriptive clauses to clearly explain what the intern will do and in what context.
- Emphasize learning-oriented activities, research involvement, technical exposure, or analytical work as applicable.
- Do NOT exaggerate responsibility, authority, or impact.
- Do NOT introduce tasks that are not explicitly implied by the input.
- Avoid vague phrases such as “various tasks”, “gain exposure”, or “work on multiple activities”.
- Maintain a professional, academic, and neutral tone suitable for international students.
- Ensure the tasks reflect realistic, supervised internship work within a university or research environment.
- Format the output strictly as 5 bullet points (no numbering, no headings).

Information:
"""

print("\n========== ROLE DESCRIPTION PROMPT ==========\n")
print(ROLE_DESCRIPTION_PROMPT)

print("\n========== TASKS PROMPT ==========\n")
print(TASKS_PROMPT)

# ================= PROMPT TEMPLATES (PERSONALISED FOR AIESEC MAHE) =================

SKILLS_PROMPT = """
You are assisting AIESEC MAHE in selecting preferred skills for an internship opportunity on the EXPA platform.

Use ONLY the provided Skills.csv file.

Task:

1) Select EXACTLY 5 skills from the CSV file.

2) Do NOT create new skills.

3) Use the exact wording as written in the CSV.

4) 1–3 words per skill.

5) Output only a comma-separated list.

6) No explanations.

Role Information:
[Paste role description here]
"""

BACKGROUND_PROMPT = """
You are assisting AIESEC MAHE in selecting preferred academic backgrounds for an internship opportunity on the EXPA platform.

Use ONLY the provided Backgrounds.csv file.

Task:

1) Select 1–3 relevant backgrounds from the CSV file.

2) Do NOT create new backgrounds.

3) Use the exact wording as written in the CSV.

4) Keep the selection academically aligned with the role.

5) Output only a comma-separated list.

6) No explanations.

Role Information:
[Paste role description here]
"""

print("\n========== SKILLS PROMPT ==========\n")
print(SKILLS_PROMPT)

print("\n========== BACKGROUND PROMPT ==========\n")
print(BACKGROUND_PROMPT)

import pandas as pd

# Load main responses CSV
df = pd.read_csv(MAIN_CSV)
df.columns = df.columns.str.strip().str.lower()

# Convert sheet row → dataframe index
idx = ROW_NUMBER - 2
row = df.iloc[idx]

# Extract relevant fields safely
basic_skills_text = str(row.get("basic skills required", "")).strip()
preferred_background_text = str(row.get("preferred academic background", "")).strip()

# ---------------- STUDY LEVEL LOGIC ----------------
def infer_study_level(text):
    text = text.lower()
    if any(k in text for k in ["phd", "doctorate"]):
        return "Doctorate"
    if any(k in text for k in ["master", "msc", "m.tech", "mba"]):
        return "Masters"
    if any(k in text for k in ["bachelor", "graduate", "bs", "be", "b.tech"]):
        return "Bachelor"
    if any(k in text for k in ["12", "high school"]):
        return "High School"
    return "Bachelor"  # safe default for EXPA

study_level = infer_study_level(preferred_background_text)

print("Minimum Study Level:", study_level)

import re

# Read correct column
duration_text = str(row.get("duration of internship", "")).lower()

# Extract numbers from duration text
weeks = re.findall(r"\d+", duration_text)

# Convert extracted numbers to integers
weeks = [int(w) for w in weeks] if weeks else []

# Default stipend
stipend = 0

# Classification logic
if 13 in weeks:
    stipend = 6500
elif any(6 <= w <= 8 for w in weeks):
    stipend = 0
else:
    stipend = 0  # fallback

print("\n===== LOGISTICS =====")
print("Accommodation: Covered")
print("Transportation: Not Covered")
print("Food: Provided (3 meals)")
print("Computer: Not Provided")
print(f"Gross Salary: INR {stipend} per month")
print("======================")

print("\n===== SELECTION PROCESS =====")
print("CV Screening: 2 days")
print("Interview with Professor: 3 days")
print("-----------------------------")
print("Estimated total process time: 5 days")
print("=============================\n")